version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: notes-app-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: notes-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - notes-app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes-app-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/notes-app
    depends_on:
      - mongodb
    networks:
      - notes-app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes-app-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - notes-app-network

volumes:
  mongodb_data:

networks:
  notes-app-network:
    driver: bridge
