version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: notes-app-mongodb-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: notes-app
    volumes:
      - mongodb_data_prod:/data/db
    networks:
      - notes-app-network
    # Don't expose port in production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes-app-backend-prod
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/notes-app
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - mongodb
    networks:
      - notes-app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes-app-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - notes-app-network

volumes:
  mongodb_data_prod:

networks:
  notes-app-network:
    driver: bridge
